"""Remove test is_active field from SystemConfig

Revision ID: 85acb9c2b7f6
Revises: 4cd99ccb2794
Create Date: 2025-08-07 19:50:20.531792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85acb9c2b7f6'
down_revision = '4cd99ccb2794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
