export const STAFF_ROLE_OPTIONS = [
  'Teacher',
  'School Administrator',
  'Director',
  'IT Support',
  'Counselor',
  'Substitute',
  'Other Staff',
] as const

export const STAFF_DEPARTMENTS = [
  'Mathematics',
  'Science',
  'English',
  'History & Social Studies',
  'Physical Education & Health',
  'Music & Arts',
  'Computer Science & Technology',
  'Administration',
  'Counseling',
  'Special Education',
  'Foreign Language',
  'Business',
] as const

export const STAFF_GRADES = [
  'Kindergarten',
  '1st',
  '2nd',
  '3rd',
  '4th',
  '5th',
  '6th',
  '7th',
  '8th',
  '9th',
  '10th',
  '11th',
  '12th',
  'N/A - Staff',
] as const

export const STAFF_PERMISSIONS: { key: string; label: string }[] = [
  { key: 'students:view', label: 'View students' },
  { key: 'students:edit', label: 'Edit student information' },
  { key: 'report_cards:view', label: 'View report cards' },
  { key: 'report_cards:generate', label: 'Generate report cards' },
  { key: 'classes:manage', label: 'Manage classes' },
  { key: 'teachers_staff:manage', label: 'Manage teachers & staff' },
  { key: 'attendance:manage', label: 'Manage attendance' },
  { key: 'assignments_grades:manage', label: 'Manage assignments & grades' },
  { key: 'communications:manage', label: 'Manage communications' },
  { key: 'billing:manage', label: 'Manage billing & financials' },
  { key: 'classes:assignable', label: 'Allow this staff member to be assigned to classes' },
]

export const EMERGENCY_RELATIONSHIPS = ['Spouse', 'Parent', 'Sibling', 'Partner', 'Friend', 'Other'] as const

export const US_STATES: { code: string; name: string }[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'District of Columbia' },
]
